# Import Pytorch

In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cu117'

# Tensor

In [3]:
import cv2
img = cv2.imread("./Utils/RGB.png")
print(img.shape)

(620, 600, 3)


In [4]:
a = torch.tensor([[1,2 , 3]])
a

tensor([[1, 2, 3]])

In [5]:
a.ndim

2

In [6]:
a[0][0].item()

1

In [7]:
a.shape

torch.Size([1, 3])

In [8]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [9]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random

In [10]:
rd = torch.rand(size=(3,4))
rd

tensor([[0.3007, 0.3699, 0.1789, 0.2905],
        [0.6855, 0.5729, 0.9901, 0.4430],
        [0.8197, 0.3354, 0.7363, 0.6426]])

# Zeros and Ones

In [11]:
zr = torch.zeros(size=(3, 4))
zr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
on = torch.ones(size=(3, 4))
on

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
on.dtype

torch.float32

In [14]:
zr = torch.zeros(size=(3, 4), dtype=torch.int32)
zr

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

# Tensor arange and tensor like

In [15]:
ar = torch.arange(1, 6, 2) # (start, end, step)
ar

tensor([1, 3, 5])

In [16]:
tensor_like_ar = torch.full_like(ar, 1)
tensor_like_ar

tensor([1, 1, 1])

In [17]:
ones_ar = torch.ones_like(ar)
ones_ar

tensor([1, 1, 1])

# Kiểu dữ liệu

In [18]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Lấy dữ liệu từ Tensor

In [20]:
rd_tensor = torch.rand(size=(3, 4))

In [24]:
rd_tensor

tensor([[0.2159, 0.3589, 0.9351, 0.7204],
        [0.4696, 0.4310, 0.5163, 0.5026],
        [0.2548, 0.7579, 0.4583, 0.5948]])

In [23]:
rd_tensor.shape;
rd_tensor.device
rd_tensor.dtype

torch.float32

# Thao tác cơ bản với tensor - Toán tử với tensor

In [35]:
tensor1 = torch.rand((1, 3))
tensor2 = torch.rand((1, 3))
tensor1, tensor2

(tensor([[0.8398, 0.8819, 0.3660]]), tensor([[0.5670, 0.9662, 0.9384]]))

## a, Toán tử cơ bản: + - * /

### Thao tác 1 tensor với 1 số

In [27]:
tensor1 + 1

tensor([[1.9866, 1.0876, 1.4429]])

In [28]:
tensor1 - 1

tensor([[-0.0134, -0.9124, -0.5571]])

In [29]:
tensor1 * 2

tensor([[1.9733, 0.1752, 0.8857]])

In [30]:
tensor1 / 2

tensor([[0.4933, 0.0438, 0.2214]])

### Thao tác 1 tensor với 1 tensor khác

In [36]:
tensor1 + tensor2

tensor([[1.4069, 1.8481, 1.3044]])

In [38]:
tensor1 - tensor2

tensor([[ 0.2728, -0.0842, -0.5724]])

In [39]:
tensor1 * tensor2

tensor([[0.4762, 0.8521, 0.3434]])

In [40]:
tensor1 / tensor2

tensor([[1.4812, 0.9128, 0.3900]])

In [ ]:
# torch.add()
# torch.sub()
# torch.multiply()
# torch.divide()

## b, Nhân Matrix Tensor (toán tử @: trong numpy)

In [41]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [42]:
tensor * tensor

tensor([1, 4, 9])

In [43]:
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
tensor @ tensor

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.37 ms, sys: 0 ns, total: 2.37 ms
Wall time: 6.18 ms


tensor(14)

In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 85 µs, sys: 0 ns, total: 85 µs
Wall time: 86.8 µs


tensor(14)