# Import Pytorch

In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cu117'

# Tensor

In [3]:
import cv2
img = cv2.imread("./Utils/RGB.png")
print(img.shape)

(620, 600, 3)


In [4]:
a = torch.tensor([[1,2 , 3]])
a

tensor([[1, 2, 3]])

In [5]:
a.ndim

2

In [6]:
a[0][0].item()

1

In [7]:
a.shape

torch.Size([1, 3])

In [8]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [9]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random

In [10]:
rd = torch.rand(size=(3,4))
rd

tensor([[0.5819, 0.1745, 0.1665, 0.7567],
        [0.6523, 0.9983, 0.4663, 0.6593],
        [0.0764, 0.2052, 0.3189, 0.1647]])

# Zeros and Ones

In [11]:
zr = torch.zeros(size=(3, 4))
zr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
on = torch.ones(size=(3, 4))
on

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
on.dtype

torch.float32

In [14]:
zr = torch.zeros(size=(3, 4), dtype=torch.int32)
zr

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

# Tensor arange and tensor like

In [15]:
ar = torch.arange(1, 6, 2) # (start, end, step)
ar

tensor([1, 3, 5])

In [16]:
tensor_like_ar = torch.full_like(ar, 1)
tensor_like_ar

tensor([1, 1, 1])

In [17]:
ones_ar = torch.ones_like(ar)
ones_ar

tensor([1, 1, 1])

# Kiểu dữ liệu

In [18]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Lấy dữ liệu từ Tensor

In [20]:
rd_tensor = torch.rand(size=(3, 4))

In [21]:
rd_tensor

tensor([[0.3019, 0.8431, 0.3676, 0.0192],
        [0.3637, 0.0339, 0.5577, 0.7541],
        [0.1136, 0.1986, 0.1396, 0.5054]])

In [22]:
rd_tensor.shape;
rd_tensor.device
rd_tensor.dtype

torch.float32

# Thao tác cơ bản với tensor - Toán tử với tensor

In [23]:
tensor1 = torch.rand((1, 3))
tensor2 = torch.rand((1, 3))
tensor1, tensor2

(tensor([[0.6801, 0.4402, 0.8978]]), tensor([[0.3695, 0.9948, 0.9506]]))

## a, Toán tử cơ bản: + - * /

### Thao tác 1 tensor với 1 số

In [24]:
tensor1 + 1

tensor([[1.6801, 1.4402, 1.8978]])

In [25]:
tensor1 - 1

tensor([[-0.3199, -0.5598, -0.1022]])

In [26]:
tensor1 * 2

tensor([[1.3602, 0.8804, 1.7955]])

In [27]:
tensor1 / 2

tensor([[0.3400, 0.2201, 0.4489]])

### Thao tác 1 tensor với 1 tensor khác

In [28]:
tensor1 + tensor2

tensor([[1.0496, 1.4350, 1.8484]])

In [29]:
tensor1 - tensor2

tensor([[ 0.3106, -0.5546, -0.0528]])

In [30]:
tensor1 * tensor2

tensor([[0.2513, 0.4379, 0.8534]])

In [31]:
tensor1 / tensor2

tensor([[1.8406, 0.4425, 0.9444]])

In [32]:
# torch.add()
# torch.sub()
# torch.multiply()
# torch.divide()

## b, Nhân Matrix Tensor (toán tử @: trong numpy)

In [33]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [34]:
tensor * tensor

tensor([1, 4, 9])

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
tensor @ tensor

tensor(14)

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 5.25 ms, total: 5.25 ms
Wall time: 4.95 ms


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 171 µs, sys: 74 µs, total: 245 µs
Wall time: 304 µs


tensor(14)

# Một số lỗi chung phổ biến trong DL:  lỗi shape

In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [40]:
# error vì không đúng chiều
# tensor_A @ tensor_B
# sửa đúng chiều
# tensor_A.T @ tensor_B

torch.transpose(tensor_A, 1, -2)

tensor([[1., 3., 5.],
        [2., 4., 6.]])

# Lớp torch.nn.Linear()

In [41]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
print(linear.weight)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)
Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Tìm min, max, mean, std, .....

In [42]:
x = torch.arange(0, 10, 1)

In [43]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 9
Mean: 4.5
Sum: 45


In [44]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(9), tensor(0), tensor(4.5000), tensor(45))

# Vị trí min/max

In [45]:
tensor = torch.arange(10)

In [47]:
print("tensor:", tensor)
print("index min:", tensor.argmin().item())
print("index max:", tensor.argmax().item())

tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
index min: 0
index max: 9


# Thay đổi kiểu dữ liệu trong tensor

In [51]:
tenInt16 = torch.tensor([1, 2, 3], dtype=torch.int16)
tenInt16

tensor([1, 2, 3], dtype=torch.int16)

In [54]:
tenInt16 = tenInt16.type(torch.int64)
tenInt16.dtype

torch.int64

# Reshaping, stacking, squeezing, unsqueezing

In [55]:
# reshape
ten = torch.arange(0, 10)
ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
ten.reshape((2,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
torch.reshape(ten, shape=(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
# view
print(ten.view(2, 5))
torch.view_copy(ten, size=(5, 2))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [79]:
# stack
ten1 = torch.arange(10).reshape(2,5)
ten2 = torch.arange(10, 20).reshape(2, 5)
print(ten1)
print(ten2)

torch.stack((ten1, ten2), dim=1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19]]])

In [80]:
# squeeze
ten 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a = ten.reshape(10, 1)
print(a)
print(a.shape)
b = a.squeeze()
print(b)
print(b.shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [96]:
# unsqueeze
b.unsqueeze(dim=1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [126]:
# permute
a.permute(0, 1).shape

torch.Size([10, 1])

# Chỉ số, lấy dữ liệu tử tensor

In [1]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [4]:
x[:, 0], x[:, 1:3, :2]

(tensor([[1, 2, 3]]),
 tensor([[[4, 5],
          [7, 8]]]))

# Pytorch Tensor && Numpy Array