# Import Pytorch

In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cu117'

# Tensor

In [3]:
import cv2
img = cv2.imread("./Utils/RGB.png")
print(img.shape)

(620, 600, 3)


In [6]:
a = torch.tensor([[1,2 , 3]])
a

tensor([[1, 2, 3]])

In [9]:
a.ndim

2

In [16]:
a[0][0].item()

1

In [20]:
a.shape

torch.Size([1, 3])

In [21]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random

In [24]:
rd = torch.rand(size=(3,4))
rd

tensor([[0.7241, 0.8427, 0.8053, 0.9273],
        [0.5204, 0.0860, 0.5999, 0.7973],
        [0.8827, 0.3033, 0.6519, 0.1351]])

# Zeros and Ones

In [25]:
zr = torch.zeros(size=(3, 4))
zr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
on = torch.ones(size=(3, 4))
on

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
on.dtype

torch.float32

In [28]:
zr = torch.zeros(size=(3, 4), dtype=torch.int32)
zr

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

# Tensor arange and tensor like

In [29]:
ar = torch.arange(1, 6, 2) # (start, end, step)
ar

tensor([1, 3, 5])

In [32]:
tensor_like_ar = torch.full_like(ar, 1)
tensor_like_ar

tensor([1, 1, 1])

In [33]:
ones_ar = torch.ones_like(ar)
ones_ar

tensor([1, 1, 1])

# Kiểu dữ liệu

In [34]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [35]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16