# Import Pytorch

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.13.1+cu117'

# Tensor

In [4]:
import cv2
img = cv2.imread("./Utils/RGB.png")
print(img.shape)

(620, 600, 3)


In [5]:
a = torch.tensor([[1,2 , 3]])
a

tensor([[1, 2, 3]])

In [6]:
a.ndim

2

In [7]:
a[0][0].item()

1

In [8]:
a.shape

torch.Size([1, 3])

In [9]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [10]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random

In [11]:
rd = torch.rand(size=(3,4))
rd

tensor([[0.1109, 0.2210, 0.0637, 0.0924],
        [0.1072, 0.9946, 0.5029, 0.9267],
        [0.7571, 0.4721, 0.4508, 0.5712]])

# Zeros and Ones

In [12]:
zr = torch.zeros(size=(3, 4))
zr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
on = torch.ones(size=(3, 4))
on

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
on.dtype

torch.float32

In [15]:
zr = torch.zeros(size=(3, 4), dtype=torch.int32)
zr

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

# Tensor arange and tensor like

In [16]:
ar = torch.arange(1, 6, 2) # (start, end, step)
ar

tensor([1, 3, 5])

In [17]:
tensor_like_ar = torch.full_like(ar, 1)
tensor_like_ar

tensor([1, 1, 1])

In [18]:
ones_ar = torch.ones_like(ar)
ones_ar

tensor([1, 1, 1])

# Kiểu dữ liệu

In [19]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [20]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Lấy dữ liệu từ Tensor

In [21]:
rd_tensor = torch.rand(size=(3, 4))

In [22]:
rd_tensor

tensor([[0.0726, 0.1655, 0.1519, 0.8109],
        [0.4538, 0.7233, 0.3319, 0.6864],
        [0.8285, 0.8575, 0.7435, 0.0736]])

In [23]:
rd_tensor.shape;
rd_tensor.device
rd_tensor.dtype

torch.float32

# Thao tác cơ bản với tensor - Toán tử với tensor

In [24]:
tensor1 = torch.rand((1, 3))
tensor2 = torch.rand((1, 3))
tensor1, tensor2

(tensor([[0.8425, 0.5151, 0.4500]]), tensor([[0.7303, 0.4338, 0.7071]]))

## a, Toán tử cơ bản: + - * /

### Thao tác 1 tensor với 1 số

In [25]:
tensor1 + 1

tensor([[1.8425, 1.5151, 1.4500]])

In [26]:
tensor1 - 1

tensor([[-0.1575, -0.4849, -0.5500]])

In [27]:
tensor1 * 2

tensor([[1.6851, 1.0303, 0.9000]])

In [28]:
tensor1 / 2

tensor([[0.4213, 0.2576, 0.2250]])

### Thao tác 1 tensor với 1 tensor khác

In [29]:
tensor1 + tensor2

tensor([[1.5728, 0.9489, 1.1571]])

In [30]:
tensor1 - tensor2

tensor([[ 0.1122,  0.0813, -0.2572]])

In [31]:
tensor1 * tensor2

tensor([[0.6153, 0.2235, 0.3182]])

In [32]:
tensor1 / tensor2

tensor([[1.1537, 1.1874, 0.6363]])

In [33]:
# torch.add()
# torch.sub()
# torch.multiply()
# torch.divide()

## b, Nhân Matrix Tensor (toán tử @: trong numpy)

In [34]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
tensor @ tensor

tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 759 µs, sys: 502 µs, total: 1.26 ms
Wall time: 749 µs


tensor(14)

In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 112 µs, sys: 74 µs, total: 186 µs
Wall time: 211 µs


tensor(14)

# Một số lỗi chung phổ biến trong DL:  lỗi shape

In [40]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [41]:
# error vì không đúng chiều
# tensor_A @ tensor_B
# sửa đúng chiều
# tensor_A.T @ tensor_B

torch.transpose(tensor_A, 1, -2)

tensor([[1., 3., 5.],
        [2., 4., 6.]])

# Lớp torch.nn.Linear()

In [42]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
print(linear.weight)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)
Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Tìm min, max, mean, std, .....

In [43]:
x = torch.arange(0, 10, 1)

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 9
Mean: 4.5
Sum: 45


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(9), tensor(0), tensor(4.5000), tensor(45))

# Vị trí min/max

In [46]:
tensor = torch.arange(10)

In [47]:
print("tensor:", tensor)
print("index min:", tensor.argmin().item())
print("index max:", tensor.argmax().item())

tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
index min: 0
index max: 9


# Thay đổi kiểu dữ liệu trong tensor

In [48]:
tenInt16 = torch.tensor([1, 2, 3], dtype=torch.int16)
tenInt16

tensor([1, 2, 3], dtype=torch.int16)

In [49]:
tenInt16 = tenInt16.type(torch.int64)
tenInt16.dtype

torch.int64

# Reshaping, stacking, squeezing, unsqueezing

In [50]:
# reshape
ten = torch.arange(0, 10)
ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
ten.reshape((2,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
torch.reshape(ten, shape=(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [53]:
# view
print(ten.view(2, 5))
torch.view_copy(ten, size=(5, 2))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [54]:
# stack
ten1 = torch.arange(10).reshape(2,5)
ten2 = torch.arange(10, 20).reshape(2, 5)
print(ten1)
print(ten2)

torch.stack((ten1, ten2), dim=1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19]]])

In [55]:
# squeeze
ten 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a = ten.reshape(10, 1)
print(a)
print(a.shape)
b = a.squeeze()
print(b)
print(b.shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [57]:
# unsqueeze
b.unsqueeze(dim=1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [58]:
# permute
a.permute(0, 1).shape

torch.Size([10, 1])

# Chỉ số, lấy dữ liệu tử tensor

In [59]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [61]:
x[:, 0], x[:, 1:3, :2]

(tensor([[1, 2, 3]]),
 tensor([[[4, 5],
          [7, 8]]]))

# Pytorch Tensor && Numpy Array

In [67]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
array_numpy = tensor.numpy()
array_numpy, tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [77]:
import numpy as np
ndarray = np.arange(10)
ndarray,

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [78]:
tensor = torch.from_numpy(ndarray)
ndarray, tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

# Cố gắng tái sãn xuất ( lấy ngẫu nhiên ra khỏi ngẫu nhiên )

In [ ]:
####